Merge User page, color themes, and Playlist Editor Page
5vSTzde4xs8h/MusiLog pull request #91
Opened 2024-04-21 05:07 UTC by Aleyva250

2024-04-21 05:55 UTC, creyes60 approved these changes

2024-04-21 06:08 UTC, cmorales1995 approved these changes

2024-04-21 06:10 UTC, creyes60 approved these changes
Good!

2024-04-21 06:53 UTC, 5vSTzde4xs8h requested changes
Short list of changes requested:

- Review the specific comments I added
- Your code has some weird formatting, please run it through the google-java-format plugin
- Fix your Javadoc (read below)

There's a severe lack of Javadoc comments for your classes. Each class, class variable, and class method needs to have a Javadoc comment. Javadoc comments are in the format

```java
/**
 * Comment here...
 */
```

for a multi-line comment or `/** Comment here... */` for a single-line comment. Javadoc comments **always** start with `/**`. Comments that start with `//` are **not** Javadoc comments.

Class comments should include an `@author` and `@since` tag:

```java
/**
 * A class for cookies.
 * 
 * @author Poleon Banouvong
 * @since 2024-04-20
 */
public class Cookies {}
```

Class variable comments require a description only:

```java
/** The flavour of the cookie. */
public String flavour;
```

Class methods should include a `@param` tag for every parameter, and a `@return` tag if the method returns a value:

```java
/**
 * Eats cookies.
 * 
 * @param flavour The flavour of the cookies to eat
 * @param quantity The number of cookies to eat
 */
public void eatCookies(String flavour, int quantity) {}

/**
 * Bakes cookies.
 * 
 * @param flavour The flavour of the cookies to bake
 * @param quantity The number of cookies to bake
 * @return The list of cookies baked
 */
public static List<Cookie> bakeCookies(String flavour, int quantity) {}
```

2024-04-21 06:53 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/EditablePlaylistAdapter.java
> +class playlistVH extends RecyclerView.ViewHolder{
Class name `playlistVH` should start with a capital letter, like literally every other Java class.

2024-04-21 06:53 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/EditablePlaylistAdapter.java
> +class playlistVH extends RecyclerView.ViewHolder{
This class should either be an *inner class* of EditablePlaylistAdapter (since it isn't being used anywhere else), or in it's own file. Class files should not contain multiple top-level classes.

2024-04-21 06:53 UTC, 5vSTzde4xs8h commented on app/src/main/res/layout/activity_entry.xml
The name of this layout isn't descriptive enough. By normal convention, this is the layout for an Entry activity, but no such activity exists. It appears to be used as the layout in EditablePlaylistAdapter, so it should be named similarly, perhaps `editable_playlist_item`.

2024-04-21 06:53 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/PlaylistEditor.java
This should be named `PlaylistEditorActivity`, to keep in line with the names of the other activities.

2024-04-23 22:25 UTC, 5vSTzde4xs8h requested changes

2024-04-23 22:25 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/UserActivity.java
> +public class UserActivity extends AppCompatActivity {
Why does this class have 2 Javadoc comments?

2024-04-23 22:25 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/UserActivity.java
> +    editorButton = (Button) findViewById(R.id.EditPlaylist_Button);
This comment shouldn't be a Javadoc comment (this is not a class variable, it's just a normal variable).

2024-04-23 22:25 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/UserActivity.java
> +    editorButton.setOnClickListener(
This comment shouldn't be a Javadoc comment (this isn't a class, class variable, or class method).

2024-04-24 03:35 UTC, cmorales1995 approved these changes

2024-04-25 18:32 UTC, 5vSTzde4xs8h approved these changes
Fix your Javadoc.

2024-04-25 19:00 UTC, closed without merging