Settings Page UI
5vSTzde4xs8h/MusiLog pull request #94
Opened 2024-04-23 03:55 UTC by creyes60

2024-04-23 04:09 UTC, 5vSTzde4xs8h requested changes
Some of the class variables and methods in `SettingsActivity` are either missing or have incomplete Javadoc (review specific comments). Please also run your code through the google-java-format plugin.

2024-04-23 04:09 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/util/SettingsActivity.java
> + */
Please add `@author` and `@since` tags.

2024-04-23 04:09 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/util/SettingsActivity.java
> +    private Button btnCreatorsInfo;
Each of these class variables needs their own Javadoc comment.

2024-04-23 04:09 UTC, 5vSTzde4xs8h commented on app/src/main/java/com/jvn/musilog/util/SettingsActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
This method is missing a Javadoc comment.

2024-04-24 03:33 UTC, cmorales1995 submitted a review, later dismissed
looks good

2024-04-25 18:33 UTC, 5vSTzde4xs8h approved these changes
Fix your Javadoc.

2024-04-25 18:59 UTC, Aleyva250 approved these changes
yes

2024-04-25 19:02 UTC, 5vSTzde4xs8h approved these changes
Fix your Javadoc.

2024-04-25 19:05 UTC, cmorales1995 approved these changes

2024-04-25 19:05 UTC, merged